# Generated by Django 3.2.13 on 2023-07-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230710_2303'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailVerifivation',
            new_name='EmailVerification',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users_images', verbose_name='Изображание пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified_email',
            field=models.BooleanField(default=False, verbose_name='Факт подтверждения электрононй почты'),
        ),
    ]
