# Generated by Django 3.2.13 on 2023-08-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='basket_history',
            field=models.JSONField(default=dict, verbose_name='Товары в доставке'),
        ),
    ]
